channels:
  - nordicesmhub
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - xarray
  - cartopy
  - matplotlib
  - matplotlib-venn
  - netcdf4
  - tqdm
  - rasterio
  - pandoc
  - html5lib
  - ipython_genutils
  - ipyvolume
  - ipywidgets
  - jupyter_latex_envs
  - jupyter_contrib_nbextensions
  - nbconvert
  - nbformat
  - nodejs
  - ipypublish

