channels:
  - nordicesmhub
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - matplotlib_venn
  - ipywidgets
  - jupyter_latex_envs
  - jupyter_contrib_nbextensions
  - nbinteract

